title: Ivan Sotomayor
logo: /assets/img/circular_portrait.png
description: Online Portfolio
show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: http://example.com/download.zip
  another_url: https://www.google.com/
